# SITE CONFIGURATION
baseurl: ""
url: "https://sylhare.github.io"
title: "Sylhare's blog"
description: "Well, here it is"

# THEME-SPECIFIC CONFIGURATION
# Meta
avatar: assets/img/rocket-icon.png
color_image: assets/img/lineart.png # In post when you set color
favicon: assets/favicon.ico

# Header and footer text
header_text: Well, here it is.
header_feature_image: assets/img/pexels/circuit.jpeg
footer_text: >
  Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a></br>copyright <a href="https://github.com/sylhare">sylhare</a> Â© <a href="https://github.com/sylhare/sylhare.github.io">ğŸ‘¨â€ğŸ’»</a>

# Blog
excerpt: truncate

# Scripts / Features
google_analytics: "UA-142123817-1"
google_analytics_ga4: "G-YPX3TXS4S4"
katex: true # Enable if using math markup
mermaid: true
cusdis_app_id: "fb06ba3d-43ad-4e00-be04-0828fac06b89"
color_theme: light  # auto, dark or light

# Post navigation
post_navigation: true

# Colours, typography and padding
# Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
paginate: 10
paginate_path: "blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# RSS
feed:
  disable_in_development: true
  excerpt_only: true
  posts_limit: 100

# BUILD SETTINGS
sass:
  style: compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
incremental: true
exclude: ["Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", ".idea", ".github", "SECURITY.md",
          "LICENSE", "README.md", "screenshot.png", "package.json", "node_modules/**", "gulpfile.js", "themes", "_draft",
          "vendor/*", ".git"]
keep_files: ["assets/example", "assets/notebook", "assets/sound", "assets/js", "assets/img",]
remote_theme: sylhare/Type-on-Strap
# theme: type-on-strap # Sends warnings on GitHub pages
